#include <stdint.h>
#include "stm32f.h"
#include "delay.h"

#include <string.h>
#include "smallfonts.h"

/*
   dc   pb4
   res  pb5
   cs   pb6
   //sclk pb13 (clk)
   //sdin pb15 (mosi)
   sclk pb15 (clk)
   sdin pb13 (mosi)
 */

#define DCPIN 4
#define RSTPIN 5
#define CSPIN 6
//#define SDCLKPIN 13
//#define SDINPIN 15
#define SDCLKPIN 15
#define SDINPIN 13

#define DC(x)					x ? (gpio_set(GPIOB_BASE, 1 << DCPIN)) : (gpio_reset(GPIOB_BASE, 1 << DCPIN));
#define CS(x)					x ? (gpio_set(GPIOB_BASE, 1 << CSPIN)) : (gpio_reset(GPIOB_BASE, 1 << CSPIN));
#define SCLK(x)				x ? (gpio_set(GPIOB_BASE, 1 << SDCLKPIN)) : (gpio_reset(GPIOB_BASE, 1 << SDCLKPIN));
#define SDIN(x)				x ? (gpio_set(GPIOB_BASE, 1 << SDINPIN)) : (gpio_reset(GPIOB_BASE, 1 << SDINPIN));
#define RST(x)					x ? (gpio_set(GPIOB_BASE, 1 << RSTPIN)) : (gpio_reset(GPIOB_BASE, 1 << RSTPIN));

uint8_t frame_buffer[128 * 64 / 8];

static void send(uint8_t byte) {
  int8_t i;
  SCLK(1);
  for (i=7; i>=0; i--) {
    SCLK(0);
    SDIN(byte & (1 << i));
    SCLK(1);
  }
}

/**
 * @brief  Writes command to the LCD
 * @param LCD_Reg: address of the selected register.
 * @arg LCD_RegValue: value to write to the selected register.
 * @retval : None
 */
void oled_cmd(uint8_t reg) {
  CS(1);
  DC(0);
  CS(0);
  send(reg);
  CS(1);
}

static void oled_data(uint8_t data) {
  CS(1);
  DC(1);
  CS(0);
  send(data);
  CS(1);
}

void oled_refresh(void) {
  oled_cmd(0x00);//---set low column address
  oled_cmd(0x10);//---set high column address
  oled_cmd(0x40);//--set start line address

  oled_cmd(0x22);//---set address
  oled_cmd(0x00);//---set start page address
  oled_cmd(0x07);//--set end page address

  uint16_t i;
  for (i=0; i<1024; i++) {
    oled_data(frame_buffer[i]);
  }
}

void oled_clear(void) {
  memset(frame_buffer, 0, 1024);
  oled_refresh();
}

void oled_setpixel(uint8_t x, uint8_t y) {
  if ((x >= 128) || (y >= 64))
    return;
  frame_buffer[x+(y/8)*128] |= 1 << (y%8);
}

void oled_delpixel(uint8_t x, uint8_t y) {
  if ((x >= 128) || (y >= 64))
    return;

  frame_buffer[x+ (y/8)*128] &= ~(1 << y%8);
}

static void oled_drawchar1(uint8_t x, uint8_t y, uint8_t c, struct FONT_DEF font, char inverted) {
  uint8_t col, column[font.u8Width];

  // Check if the requested character is available
  if ((c >= font.u8FirstChar) && (c <= font.u8LastChar)) {
    // Retrieve appropriate columns from font data
    for (col = 0; col < font.u8Width; col++) {
      column[col] = font.au8FontTable[((c - 32) * font.u8Width) + col]; // Get first column of appropriate character
    }
  } else {
    // Requested character is not available in this font ... send a space instead
    for (col = 0; col < font.u8Width; col++) {
      column[col] = 0xFF; // Send solid space
    }
  }

  // Render each column
  uint8_t xoffset, yoffset;
  for (xoffset = 0; xoffset < font.u8Width; xoffset++) {
    for (yoffset = 0; yoffset < (font.u8Height + 1); yoffset++) {
      if ((column[xoffset] >> yoffset) & 1) {
        if(inverted)
          oled_delpixel(x + xoffset, y + yoffset);
        else
          oled_setpixel(x + xoffset, y + yoffset);
      } else {
        if(inverted)
          oled_setpixel(x + xoffset, y + yoffset);
        else
          oled_delpixel(x + xoffset, y + yoffset);
      }
    }
  }
}

void oled_print_inv(uint8_t x, uint8_t y, char* text, struct FONT_DEF font) {
  uint8_t l;
  for (l = 0; l < strlen(text); l++) {
    oled_drawchar1(x + (l * (font.u8Width)), y, text[l], font, 1);
  }
  oled_refresh();
}

void oled_print(uint8_t x, uint8_t y, char* text, struct FONT_DEF font) {
  uint8_t l;
  for (l = 0; l < strlen(text); l++) {
    oled_drawchar1(x + (l * (font.u8Width)), y, text[l], font, 0);
  }
  oled_refresh();
}

void oled_init(void) {      //Generated by Internal DC/DC Circuit // VCC externally supplied
  GPIO_Regs *greg;

  /* Enable GPIOD clock */
  MMIO32(RCC_AHB1ENR) |= RCC_AHB1Periph_GPIOB;

  greg = (GPIO_Regs *) GPIOB_BASE;
  greg->MODER  &= (unsigned int) ~((3 << (4 << 1))  |
                                   (3 << (5 << 1))  |
                                   (3 << (6 << 1))  |
                                   (3 << (13 << 1))  |
                                   (3 << (15 << 1))
                                   );
  greg->PUPDR  &= (unsigned int) ~((3 << (4 << 1))  |
                                   (3 << (5 << 1))  |
                                   (3 << (6 << 1))  |
                                   (3 << (13 << 1))  |
                                   (3 << (15 << 1))
                                   );
  greg->MODER |=   ((GPIO_Mode_OUT << (4 << 1))  |
                    (GPIO_Mode_OUT << (5 << 1))  |
                    (GPIO_Mode_OUT << (6 << 1))  |
                    (GPIO_Mode_OUT << (13 << 1))  |
                    (GPIO_Mode_OUT << (15 << 1))
                    );
  greg->PUPDR |= ((GPIO_PuPd_UP << (4 << 1)) |
                  (GPIO_PuPd_UP << (5 << 1)) |
                  (GPIO_PuPd_UP << (6 << 1)) |
                  (GPIO_PuPd_UP << (13 << 1)) |
                  (GPIO_PuPd_UP << (15 << 1))
                  );
  greg->OSPEEDR |= ((GPIO_Speed_100MHz << (4 << 1))  |
                    (GPIO_Speed_100MHz << (5 << 1))  |
                    (GPIO_Speed_100MHz << (6 << 1))  |
                    (GPIO_Speed_100MHz << (13 << 1))  |
                    (GPIO_Speed_100MHz << (15 << 1))
                    );

  RST(1);
  uDelay(2);
  RST(0);
  mDelay(10);
  RST(1);
  uDelay(2);

  oled_cmd(0xae);//--turn off oled panel
  oled_cmd(0x20);//---set page addressing mode
  oled_cmd(0x00);// 0x02
  // if address mode 02
  //oled_cmd(0x00);//---set low column address
  //oled_cmd(0x10);//---set high column address
  //oled_cmd(0x40);//--set start line address
  // if address mode 00
  oled_cmd(0x21);//---set column address
  oled_cmd(0x00);//---set start column address
  oled_cmd(0x7f);//--set end column address
  oled_cmd(0x22);//---set address
  oled_cmd(0x00);//---set start page address
  oled_cmd(0x07);//--set end page address
  oled_cmd(0x81);//--set contrast control register
  oled_cmd(0xcf);
  //oled_cmd(0xa0);//--set segment re-map 95 to 0
  // rotate 180
  oled_cmd(0xa1);
  oled_cmd(0xc8); // COMSCANDEC - 0xc0 is comscaninc, but ususally in reset anyway. so unset

  oled_cmd(0xa6);//--set normal display
  oled_cmd(0xa4);//--set display all on resume
  oled_cmd(0xa8);//--set multiplex ratio(1 to 64)
  oled_cmd(0x3f);//--1/64 duty
  oled_cmd(0xd3);//--set display offset
  oled_cmd(0x00);//--not offset
  oled_cmd(0xd5);//--set display clock divide ratio/oscillator frequency
  oled_cmd(0x80);//--set divide ratio
  oled_cmd(0xd9);//--set pre-charge period
  oled_cmd(0xf1);
  oled_cmd(0xda);//--set com pins hardware configuration
  oled_cmd(0x12);
  oled_cmd(0xdb);//--set vcomh
  oled_cmd(0x40);
  oled_cmd(0x8d);//--set Charge Pump enable/disable
  oled_cmd(0x14);//--set(0x14) enable
  oled_cmd(0xaf);//--turn on oled panel

  uDelay(100);
  oled_clear();
}
